### ISSUE TITLE
Capturing a control point does not change hologram

### ISSUE THREAD

**Issue by ttenpi** [JLyne/blap-2019-plugin#2]
Pre-captured control points have the correct hologram colour, but when a point is captured it does not trigger a change of the hologram colour.

KOTH https://i.imgur.com/dmXd7Sz.jpg  
5CP pre-captured https://i.imgur.com/U1Ytu7R.jpg  
5CP post-capture https://i.imgur.com/U1Ytu7R.jpg  
PL past CP https://i.imgur.com/NPGAgCI.jpg
Also tested on Attack/Defend CP, same thing.
(some meme map too https://i.imgur.com/QeLvgRX.jpg)

Was tested on redsun.tf servers.

Note: the Stop That Tank (STT) gamemode replaces the holograms of captured control points with the MvM bot walking direction holograms (the blue arrows with the walking soldier). The STT plugin does this correctly, perhaps there's something from their code you can borrow.

**Comment by JLyne** [comment]
Can't seem to reproduce this, at least on the stock PL and KOTH maps I tried.
Feel like there might be something else going on here, as your screenshots suggest the donation total isn't rotating along with the control point hologram. Is this the case?

**Comment by FortyTwoFortyTwo** [comment]
Donation total indeed isn't rotating with the hologram, donation update works fine however.

**Comment by JLyne** [comment]
Tried this on a handful of servers now and does seem to be an issue specific to redsun.
Not sure what to suggest here, since I know little about your setup etc. I'm also not doing anything particularly complex with control points, just setting the model and parenting some sprites, so unsure what there would be breaking. 

All I can say right now is `blap_cps_enabled 0` would at least fix the capture issue, by disabling the cp reskinning (It'll also break rotating but that's already broken).

**Comment by FortyTwoFortyTwo** [comment]
Turns out adding models/materials to just fastdl FTP isn't enough, have to also upload to all servers.
You are indeed correct that it our fault, whoops!

**Comment by JLyne** [comment]
No problem, glad you got it sorted
